#ifndef SENSORS_SYSLOC_LOCATIONS_H_INCLUDED
#define SENSORS_SYSLOC_LOCATIONS_H_INCLUDED

typedef enum {

    SENSORS_LOC_CONFIGLOAD_ERROR,
    SENSORS_LOC_CONFIGVERSION_ERROR,
    SENSORS_LOC_READY,

    SENSORS_LOC_MAP_FAILED,
    SENSORS_LOC_MAP_VALIDATED,

    SENSORS_LOC_O2_FAILED,
    SENSORS_LOC_O2_VALIDATED,

    SENSORS_LOC_TPS_FAILED,
    SENSORS_LOC_TPS_VALIDATED,

    SENSORS_LOC_IAT_FAILED,
    SENSORS_LOC_IAT_VALIDATED,

    SENSORS_LOC_CLT_FAILED,
    SENSORS_LOC_CLT_VALIDATED,

    SENSORS_LOC_VBAT_FAILED,
    SENSORS_LOC_VBAT_VALIDATED,

    SENSORS_LOC_KNOCK_FAILED,
    SENSORS_LOC_KNOCK_VALIDATED,

    SENSORS_LOC_BARO_FAILED,
    SENSORS_LOC_BARO_VALIDATED,

    SENSORS_LOC_GEAR_FAILED,
    SENSORS_LOC_GEAR_VALIDATED,


    SENSORS_LOC_COUNT



} sensors_sysloc_locations_t;




#endif // SENSORS_SYSLOC_LOCATIONS_H_INCLUDED
