#ifndef IGNITION_SYSLOC_LOCATIONS_H_INCLUDED
#define IGNITION_SYSLOC_LOCATIONS_H_INCLUDED

typedef enum {

    IGNITION_LOC_CONFIGLOAD_ERROR,
    IGNITION_LOC_CONFIGVERSION_ERROR,
    IGNITION_LOC_READY,

    IGNITION_LOC_DYN_CTRLS_INVALID_ADVANCE,
    IGNITION_LOC_DYN_CTRLS_INVALID_DWELL,

    IGNITION_LOC_SEQUENTIAL_FAIL,




    IGNITION_LOC_COUNT



} ignition_sysloc_locations_t;




#endif // IGNITION_SYSLOC_LOCATIONS_H_INCLUDED
