#ifndef IGNITION_SYSLOC_LOCATIONS_H_INCLUDED
#define IGNITION_SYSLOC_LOCATIONS_H_INCLUDED

typedef enum {

    IGNITION_LOC_CONFIG_LOAD_FAIL,
    IGNITION_LOC_CONFIG_VERSION_MISMATCH,
    IGNITION_LOC_CONFIG_LOAD_SUCCESS,

    IGNITION_LOC_DYN_CTRLS_INVALID_ADVANCE,
    IGNITION_LOC_DYN_CTRLS_INVALID_DWELL,








    IGNITION_LOC_COUNT



} ignition_sysloc_locations_t;




#endif // IGNITION_SYSLOC_LOCATIONS_H_INCLUDED
