#ifndef CONSOLE_SYSLOG_LOCATIONS_H_INCLUDED
#define CONSOLE_SYSLOG_LOCATIONS_H_INCLUDED

typedef enum {

    CONSOLE_LOC_SENSORCALIB_MOD_PERM_GIVEN,
    CONSOLE_LOC_IGNCONF_MOD_PERM_GIVEN,
    CONSOLE_LOC_FUELCONF_MOD_PERM_GIVEN,
    CONSOLE_LOC_DECODERCONF_MOD_PERM_GIVEN,
    CONSOLE_LOC_TUAREGSETUP_MOD_PERM_GIVEN,
    CONSOLE_LOC_CTRLSET_MAP_MOD_PERM_GIVEN,
    CONSOLE_LOC_CTRLSET_TPS_MOD_PERM_GIVEN,
    CONSOLE_LOC_CTRLSET_TPS_LIMP_MOD_PERM_GIVEN,

    CONSOLE_LOC_BURN_PERM_GIVEN,
    CONSOLE_LOC_FAULTLOG_PERM_GIVEN,
    CONSOLE_LOC_LOCK_CONFIG,
    CONSOLE_LOC_COUNT

} console_syslog_locations_t;




#endif // CONSOLE_SYSLOG_LOCATIONS_H_INCLUDED
