#ifndef TUNERSTUDIO_SYSLOG_LOCATIONS_H_INCLUDED
#define TUNERSTUDIO_SYSLOG_LOCATIONS_H_INCLUDED

typedef enum {

    TS_LOC_NOMODPERM,
    TS_LOC_MOD_ERROR,
    TS_LOC_NOBRNPERM,
    TS_LOC_BRN_ERROR,

    TS_LOC_COUNT



} ts_syslog_locations_t;




#endif // TUNERSTUDIO_SYSLOG_LOCATIONS_H_INCLUDED
