#ifndef DECODER_SYSLOG_H_INCLUDED
#define DECODER_SYSLOG_H_INCLUDED


typedef enum {



    DECODER_LOC_CONFIGLOAD_ERROR,
    DECODER_LOC_CONFIGVERSION_ERROR,
    DECODER_LOC_READY,
    DECODER_LOC_HALTED,

    DECODER_LOC_HW_SET_CRANK_SENSING_INVERT,
    DECODER_LOC_HW_SET_CRANK_SENSING_ARG,
    DECODER_LOC_HW_UPD_CRANK_NOISEF_ARG,
    DECODER_LOC_HW_SET_CAM_SENSING_INVERT,
    DECODER_LOC_HW_SET_CAM_SENSING_ARG,
    DECODER_LOC_HW_UPD_CAM_NOISEF_ARG,



    DECODER_LOC_DEBUG_ERROR,
    DECODER_LOC_SETSTATE_ERROR,

    DECODER_LOC_CRKHDL_STATE_ERROR,
    DECODER_LOC_COUNT



} Decoder_syslog_locations_t;






#endif
