#ifndef SERVICE_SYSLOC_LOCATIONS_H_INCLUDED
#define SERVICE_SYSLOC_LOCATIONS_H_INCLUDED

typedef enum {

    SERVICE_LOC_SERVICE_ENABLED,

    SERVICE_LOC_ACTIVATE_FUEL_PUMP_PERMISSION,
    SERVICE_LOC_ACTIVATE_FUEL_PUMP_END_CLIP,
    SERVICE_LOC_ACTIVATE_FUEL_PUMP_BEGIN,
    SERVICE_LOC_DEACTIVATE_FUEL_PUMP,

    SERVICE_LOC_ACTIVATE_INJECTOR1_PERMISSION,
    SERVICE_LOC_ACTIVATE_INJECTOR1_ON_CLIP,
    SERVICE_LOC_ACTIVATE_INJECTOR1_OFF_CLIP,
    SERVICE_LOC_ACTIVATE_INJECTOR1_END_CLIP,
    SERVICE_LOC_ACTIVATE_INJECTOR1_BEGIN,
    SERVICE_LOC_DEACTIVATE_INJECTOR1,

    SERVICE_LOC_ACTIVATE_INJECTOR2_PERMISSION,
    SERVICE_LOC_ACTIVATE_INJECTOR2_ON_CLIP,
    SERVICE_LOC_ACTIVATE_INJECTOR2_OFF_CLIP,
    SERVICE_LOC_ACTIVATE_INJECTOR2_END_CLIP,
    SERVICE_LOC_ACTIVATE_INJECTOR2_BEGIN,
    SERVICE_LOC_DEACTIVATE_INJECTOR2,

    SERVICE_LOC_ACTIVATE_COIL1_PERMISSION,
    SERVICE_LOC_ACTIVATE_COIL1_ON_CLIP,
    SERVICE_LOC_ACTIVATE_COIL1_OFF_CLIP,
    SERVICE_LOC_ACTIVATE_COIL1_END_CLIP,
    SERVICE_LOC_ACTIVATE_COIL1_BEGIN,
    SERVICE_LOC_DEACTIVATE_COIL1,

    SERVICE_LOC_ACTIVATE_COIL2_PERMISSION,
    SERVICE_LOC_ACTIVATE_COIL2_ON_CLIP,
    SERVICE_LOC_ACTIVATE_COIL2_OFF_CLIP,
    SERVICE_LOC_ACTIVATE_COIL2_END_CLIP,
    SERVICE_LOC_ACTIVATE_COIL2_BEGIN,
    SERVICE_LOC_DEACTIVATE_COIL2,

    SERVICE_LOC_ACTIVATE_TACH_PERMISSION,
    SERVICE_LOC_ACTIVATE_TACH_COMPARE,
    SERVICE_LOC_ACTIVATE_TACH_BEGIN,
    SERVICE_LOC_DEACTIVATE_TACH,

    SERVICE_LOC_DEBUGOUTPUT_ENABLED,

    SERVICE_LOC_COUNT



} service_sysloc_locations_t;




#endif // SERVICE_SYSLOC_LOCATIONS_H_INCLUDED
