#ifndef TUAREG_SYSLOC_LOCATIONS_H_INCLUDED
#define TUAREG_SYSLOC_LOCATIONS_H_INCLUDED

typedef enum {

    TUAREG_LOC_SET_RUNMODE_LIMP_EXIT,

    TUAREG_LOC_SET_RUNMODE_LOAD_CONFIG_FAIL,
    TUAREG_LOC_SET_RUNMODE_LOAD_CONFIG_SUCCESS,
    TUAREG_LOC_SET_RUNMODE_LOAD_CONFIG_VERSION_FAIL,
    TUAREG_LOC_SET_RUNMODE_ESSENTIALS_CONFIG_LOADED,
    TUAREG_LOC_SET_RUNMODE_DEFAULT_BRANCH,

    TUAREG_LOC_UPDATE_HALTSRC_CRASH_DETECTED,
    TUAREG_LOC_UPDATE_HALTSRC_SIDESTAND_DETECTED,

    TUAREG_LOC_UPDATE_RUNMODE_DEFAULT_BRANCH,
    TUAREG_LOC_SET_RUNMODE_SERVICE,








    TUAREG_LOC_COUNT



} Tuareg_sysloc_locations_t;




#endif // TUAREG_SYSLOC_LOCATIONS_H_INCLUDED
