#ifndef LPSCHED_SYSLOG_H_INCLUDED
#define LPSCHED_SYSLOG_H_INCLUDED


typedef enum {



    LPSCHED_LOC_SETCH_INITCHECK,
    LPSCHED_LOC_SETCH_PARMCHECK_CH,
    LPSCHED_LOC_SETCH_PARMCHECK_INTA,
    LPSCHED_LOC_SETCH_PARMCHECK_INTB,
    LPSCHED_LOC_SETCH_PARMCHECK_INTP,
    LPSCHED_LOC_SETCH_PARMCHECK_SEQLEN,
    LPSCHED_LOC_SETCH_PARMCHECK_CYCLES,
    LPSCHED_LOC_SETCH_PARMCHECK_POLARITY,

    LPSCHED_LOC_RESETCH_INITCHECK,
    LPSCHED_LOC_RESETCH_PARMCHECK_CH,

    LPSCHED_LOC_IRQ_INVAL_MODE,
    LPSCHED_LOC_IRQ_INVAL_INTERVAL,


    LPSCHED_LOC_COUNT



} Lowprio_scheduler_syslog_locations_t;






#endif
