#ifndef SCHEDULER_DIAGNOSTICS_H_INCLUDED
#define SCHEDULER_DIAGNOSTICS_H_INCLUDED

#include "stm32_libs/boctok_types.h"
#include "Tuareg_types.h"


typedef enum {

    SCHEDIAG_ICH1_RESET,
    SCHEDIAG_ICH2_RESET,
    SCHEDIAG_FCH1_RESET,
    SCHEDIAG_FCH2_RESET,

    SCHEDIAG_SET_ICH1_1INT,
    SCHEDIAG_SET_ICH2_1INT,
    SCHEDIAG_SET_FCH1_1INT,
    SCHEDIAG_SET_FCH2_1INT,

    SCHEDIAG_SET_ICH1_2INT,
    SCHEDIAG_SET_ICH2_2INT,
    SCHEDIAG_SET_FCH1_2INT,
    SCHEDIAG_SET_FCH2_2INT,

    SCHEDIAG_ICH1_REALLOC,
    SCHEDIAG_ICH2_REALLOC,
    SCHEDIAG_FCH1_REALLOC,
    SCHEDIAG_FCH2_REALLOC,

    SCHEDIAG_ICH1_REALLOC_COMPLETED,
    SCHEDIAG_ICH2_REALLOC_COMPLETED,
    SCHEDIAG_FCH1_REALLOC_COMPLETED,
    SCHEDIAG_FCH2_REALLOC_COMPLETED,

    SCHEDIAG_ICH1_ALLOC_CUR,
    SCHEDIAG_ICH2_ALLOC_CUR,
    SCHEDIAG_FCH1_ALLOC_CUR,
    SCHEDIAG_FCH2_ALLOC_CUR,

    SCHEDIAG_ICH1_ALLOC_PREL,
    SCHEDIAG_ICH2_ALLOC_PREL,
    SCHEDIAG_FCH1_ALLOC_PREL,
    SCHEDIAG_FCH2_ALLOC_PREL,

    SCHEDIAG_ICH1_ALLOC_UPD,
    SCHEDIAG_ICH2_ALLOC_UPD,
    SCHEDIAG_FCH1_ALLOC_UPD,
    SCHEDIAG_FCH2_ALLOC_UPD,

    SCHEDIAG_ICH1_ALLOC,
    SCHEDIAG_ICH2_ALLOC,
    SCHEDIAG_FCH1_ALLOC,
    SCHEDIAG_FCH2_ALLOC,

    SCHEDIAG_ICH1_TRIG,
    SCHEDIAG_ICH2_TRIG,
    SCHEDIAG_FCH1_TRIG,
    SCHEDIAG_FCH2_TRIG,

    SCHEDIAG_DELAY_MININT1,
    SCHEDIAG_DELAY_MININT2,
    SCHEDIAG_WRAP,

    SCHEDIAG_COUNT

} scheduler_diag_t;




void scheduler_diag_log_event(scheduler_diag_t event);
exec_result_t print_scheduler_diag(USART_TypeDef * Port);



#endif // SCHEDULER_DIAGNOSTICS_H_INCLUDED
