#ifndef BASECALC_SYSLOG_LOCATIONS_H_INCLUDED
#define BASECALC_SYSLOG_LOCATIONS_H_INCLUDED


typedef enum {


    BASECALC_LOC_CALC_ROT_ANGLE_DEG_DIV0,
    BASECALC_LOC_CALC_RPM_DIV0,

    BASECALC_LOC_DIVIDE_VU32_DIV0,
    BASECALC_LOC_DIVIDE_VF32_DIV0,
    BASECALC_LOC_DIVIDE_FLOAT_DIV0,

    BASECALC_LOC_CRKPOS_AFTER_UNDEF,
    BASECALC_LOC_OPPOSITE_PHASE_UNDEF,



    BASECALC_LOC_COUNT


} basecalc_sysloc_locations_t;


#endif // BASECALC_SYSLOG_LOCATIONS_H_INCLUDED
