#ifndef FUELING_DIAGNOSTICS_H_INCLUDED
#define FUELING_DIAGNOSTICS_H_INCLUDED

#include "stm32_libs/boctok_types.h"
#include "Tuareg_types.h"


typedef enum {

    FDIAG_UPD_CTRLS_CALLS,
    FDIAG_UPD_CTRLS_OP_PRECOND_FAIL,
    FDIAG_UPD_CTRLS_CRANKING,
    FDIAG_UPD_CTRLS_RUNNING,
    FDIAG_UPD_CTRLS_SEQ,
    FDIAG_UPD_CTRLS_BATCH,
    FDIAG_UPD_CTRLS_MAP,
    FDIAG_UPD_CTRLS_TPS,
    FDIAG_UPD_CTRLS_VE_INVAL,
    FDIAG_UPD_CTRLS_AFTTGT_INVAL,

    FDIAG_CRKPOSH_CALLS,
    FDIAG_CRKPOSH_VIT_PRECOND_FAIL,
    FDIAG_CRKPOSH_INJBEG_POS,
    FDIAG_CRKPOSH_SEQ_ERROR,
    FDIAG_CRKPOSH_INJBEG_1,
    FDIAG_CRKPOSH_INJBEG_2,

    FDIAG_UPD_BASE_FMAS_CRK_DRY,

    FDIAG_UPD_ACCELCOMP_RPMSCALED,
    FDIAG_UPD_ACCELCOMP_ACCEL,
    FDIAG_UPD_ACCELCOMP_DECEL,
    FDIAG_UPD_ACCELCOMP_TAPERED,

    FDIAG_UPD_TGTFMASS_PRECOND_FAIL,
    FDIAG_UPD_TGTFMASS_ASE_ACT,
    FDIAG_UPD_TGTFMASS_WUE_ACT,
    FDIAG_UPD_TGTFMASS_BARO_ACT,
    FDIAG_UPD_TGTFMASS_AE_ACT,
    FDIAG_UPD_TGTFMASS_ZERO,

    FDIAG_COUNT

} fueling_diag_t;


void fueling_diag_log_event(fueling_diag_t event);
exec_result_t print_fueling_diag(USART_TypeDef * Port);


#endif // FUELING_DIAGNOSTICS_H_INCLUDED
