#ifndef FUELING_SYSLOC_LOCATIONS_H_INCLUDED
#define FUELING_SYSLOC_LOCATIONS_H_INCLUDED

typedef enum {

    FUELING_LOC_CONFIG_LOAD_FAIL,
    FUELING_LOC_CONFIG_VERSION_MISMATCH,
    FUELING_LOC_CONFIG_LOAD_SUCCESS,

    FUELING_LOC_SEQUENTIAL_CALC_FAIL,
    FUELING_LOC_INJ_DEADTIME_INVALID,

    FUELING_LOC_COMPENSATION_CLIP,


    FUELING_LOC_ACCELCOMP_RPMSCALE,





    FUELING_LOC_COUNT



} fueling_sysloc_locations_t;




#endif // FUELING_SYSLOC_LOCATIONS_H_INCLUDED
