#ifndef FUELING_SYSLOC_LOCATIONS_H_INCLUDED
#define FUELING_SYSLOC_LOCATIONS_H_INCLUDED

typedef enum {

    FUELLING_LOC_CONFIG_LOAD_FAIL,
    FUELLING_LOC_CONFIG_VERSION_MISMATCH,
    FUELLING_LOC_CONFIG_LOAD_SUCCESS,



    FUELLING_LOC_COUNT



} fueling_sysloc_locations_t;




#endif // FUELING_SYSLOC_LOCATIONS_H_INCLUDED
