#ifndef STORAGE_SYSLOG_LOCATIONS_H_INCLUDED
#define STORAGE_SYSLOG_LOCATIONS_H_INCLUDED


typedef enum {

    STORAGE_LOC_T2D_DATA_RANGE,
    STORAGE_LOC_T2D_NOT_STEADY,
    STORAGE_LOC_T2D_NO_MATCH,
    STORAGE_LOC_COUNT

} Storage_sysloc_locations_t;




#endif // STORAGE_SYSLOG_LOCATIONS_H_INCLUDED
